import pygame.color

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_BACKGROUND_COLOR = pygame.Color(0, 0, 0)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 800   # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 0.3
PLAYER_SPEED = 0.2
PLAYER_SHOOT_SPEED = 0.5
PLAYER_SHOOT_COOLDOWN = 300

SHOT_RADIUS = 5